### ISSUE TITLE
Open up for contributions

### ISSUE THREAD

**Issue by mario-d-s** [reynj/reynj#1]
I'd like to contribute to this project but currently all development is happening privately. It's nice to see there is a list of features that you intend to implement but right now I can't know if you're already writing code for them so the risk of doing redundant work is high.

I think there are a few things to be done:
- [x] Fulfill GitHub's [community checklist](https://github.com/reynj/reynj/community)
  - [x] Write contributing guidelines
  - [x] Write an issue template
  - [x] Write a PR template
- [ ] Convert the feature roadmap to individual issues and track them properly (indicate when you're working on them).

If you like some help, please tell me what I can do 😃

**Comment by jochenjonc** [comment]
Hi Mario,

Thanks for your offer to help. At the moment my plan is to work towards a version 1.0.0 and after that I'm going to fulfill the checklist and make the project more open to contributors.

For me version 1.0.0 is when I have implemented the RangeCollection, including functionality like Sort, Combine, etc.

Things that are not on my list for version 1.0.0, but I want to add later are. Specific implementations like DateRange, NumericRange, ... and some real-world examples on how to use the library.

If you want you can help with this. I'll make sure we are not working on the same thing.

**Comment by jochenjonc** [comment]
All green on the community checklist :wink:.

I'll keep the issue open until I have added the roadmap.
