### ISSUE TITLE
EnumerateBy is not public yet is documented as such

### ISSUE THREAD

**Issue by NickVandewalle** [reynj/reynj#10]
The [documentation](https://github.com/reynj/reynj?tab=readme-ov-file#enumeratebyt-step-funct-t-t-stepper--enumeratebytstep-step-funct-tstep-t-stepper) showcases the `EnumerateBy` method, yet both variants I can found in the codebase are currently `protected internal`.

Is this by design and still in development, or should one of those variants simply have a different access modifier?

Thanks!

**Comment by jochenjonc** [comment]
The documentation also says:

> This function is protected and should be used in class that inherits from Range.

The idea is that you have a class, for example DateRange, that inherits from Range<DateTimeOffset>. In that DateRange class you can add one or more functions that use the EnumerateBy helper function.

The EnumerateBy can become very complex and in a lot of cases can throw exceptions during the loop when the stepper function doesn't step correctly, see the [unit tests](https://github.com/reynj/reynj/blob/24bf143483d541a581b9d02bc26ab38e35aac956/Reynj.UnitTests/RangeTests.cs#L701C1-L894C10). But if it is wrapped in a function with a special purpose for a specific type of Range<T> you can add additional safety and tests and make sure that it works for your scenario.

**Comment by NickVandewalle** [comment]
Thanks, we'll tackle it as such!
